name: Maven Build and Deploy to JBoss

on:
  push:
    branches: [ main ]
    paths:
      - '**.java'
      - 'pom.xml'
      - '.github/workflows/ci-cd.yaml'      # 🧩 Run when this file changes
  pull_request:
    branches: [ main ]
  workflow_dispatch:                        # 🧠 Allow manual runs from Actions tab

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2️⃣ Set up Java
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      # 3️⃣ Build with Maven
      - name: Build with Maven
        run: mvn clean package 

      # 4️⃣ Upload build artifact (WAR file)
      - name: Upload WAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-java-app
          path: target/*.war

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'

    steps:
      - name: Download WAR artifact
        uses: actions/download-artifact@v4
        with:
          name: my-java-app
          path: .

      - name: List downloaded files
        run: ls -R

      - name: Copy WAR to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_PEM_KEY }}
          source: "my-java-app/NETFLIX-1.2.2.war"   # ✅ dynamically finds WAR
          target: "/opt/wildfly/standalone/deployments/"

  
