name: Maven Build and Deploy to JBoss

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2️⃣ Set up Java
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      # 3️⃣ Build with Maven
      - name: Build with Maven
        run: mvn clean package 

      # 4️⃣ Upload build artifact (WAR file)
      - name: Upload WAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-java-app
          path: target/*.war

  

   
